# Generated by Django 4.2.18 on 2025-02-21 09:19

import agir.lib.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0034_alter_document_type"),
        migrations.swappable_dependency(settings.NUNTIUS_SEGMENT_MODEL),
        ("activity", "0033_auto_20230504_1721"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnouncementAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Réponse - Bannière d'annonce",
                "verbose_name_plural": "Réponses - Bannières d'annonce",
            },
        ),
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=models.CharField(
                choices=[
                    (
                        "referent_must_validate_remove_request",
                        "Requête de suppression de membre",
                    ),
                    ("waiting-payment", "Paiement en attente"),
                    (
                        "new-event-participation-mygroups",
                        "Le groupe participe à un événement",
                    ),
                    ("group-invitation", "Invitation à un groupe"),
                    ("new-follower", "Nouveau·lle abonné·e dans le groupe"),
                    ("new-member", "Nouveau membre dans le groupe"),
                    (
                        "member-status-changed",
                        "Un membre actif du groupe a été passé au statut abonné·e",
                    ),
                    (
                        "group-membership-limit-reminder",
                        "Les membres du groupes sont de plus en plus nombreux",
                    ),
                    ("new-message", "Nouveau message dans un de vos groupes"),
                    ("new-comment", "Nouveau commentaire dans un de vos groupes"),
                    (
                        "new-comment-restricted",
                        "Nouveau commentaire dans une de vos discussions",
                    ),
                    ("waiting-location-group", "Préciser la localisation du groupe"),
                    (
                        "waiting-location-event",
                        "Préciser la localisation d'un événement",
                    ),
                    ("new-event-speaker-request", "Nouvelle demande d'événement reçue"),
                    (
                        "group-coorganization-invite",
                        "Invitation à coorganiser un événement reçue",
                    ),
                    (
                        "group-coorganization-accepted",
                        "Invitation à coorganiser un événement acceptée",
                    ),
                    (
                        "group-coorganization-accepted-from",
                        "Invitation de leur groupe à coorganiser mon événement acceptée",
                    ),
                    (
                        "group-coorganization-accepted-to",
                        "Invitation de mon groupe à coorganiser leur événement acceptée",
                    ),
                    ("group-info-update", "Mise à jour des informations du groupe"),
                    (
                        "accepted-invitation-member",
                        "Invitation à rejoindre un groupe acceptée",
                    ),
                    ("new-attendee", "Un nouveau participant à votre événement"),
                    (
                        "new-group-attendee",
                        "Un nouveau groupe participant à votre événement",
                    ),
                    ("event-update", "Mise à jour d'un événement"),
                    ("new-event-mygroups", "Votre groupe organise un événement"),
                    ("new-report", "Nouveau compte-rendu d'événement"),
                    ("cancelled-event", "Événement annulé"),
                    ("referral-accepted", "Personne parrainée"),
                    ("announcement", "Associée à une annonce"),
                    (
                        "transferred-group-member",
                        "Un membre d'un groupe a été transferé vers un autre groupe",
                    ),
                    (
                        "new-members-through-transfer",
                        "De nouveaux membres ont été transferés vers le groupe",
                    ),
                    ("group-creation-confirmation", "Groupe créé"),
                    ("event-suggestion", "Événement suggéré"),
                    (
                        "reminder-docs-event-eve",
                        "Rappel à la veille d'un événement des documents à envoyer",
                    ),
                    (
                        "reminder-docs-event-nextday",
                        "Rappel au lendemain d'un événement des documents à envoyer",
                    ),
                    (
                        "reminder-report-form-for-event",
                        "Rappel au lendemain d'un événement de l'éventuel formulaire de bilan à remplir",
                    ),
                    (
                        "reminder-upcoming-event-start",
                        "Rappel du début imminent d'un événement pour les participants",
                    ),
                    (
                        "uncertifiable-group-warning",
                        "Avertissement aux animateur·ices d'un groupe certifié qui ne respecte plus les critères de certification",
                    ),
                ],
                max_length=50,
                verbose_name="Type",
            ),
        ),
        migrations.CreateModel(
            name="BannerAnnouncementAnswerTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer",
                        to="activity.announcementanswer",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banner_announcement_answer_persontag",
                        to="people.persontag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BannerAnnouncement",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="date de création",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="dernière modification"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID interne à l'API pour identifier la ressource",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "description",
                    agir.lib.models.DescriptionField(
                        blank=True,
                        help_text="Une courte description",
                        verbose_name="description",
                    ),
                ),
                (
                    "allow_html",
                    models.BooleanField(
                        default=False,
                        verbose_name="autoriser le HTML étendu dans la description",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Ce texte sera utilisé comme titre de l'annonce",
                        max_length=200,
                        verbose_name="Titre de l'annonce",
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        blank=True,
                        help_text="Question présentée aux militant·es",
                        max_length=200,
                        verbose_name="Question",
                    ),
                ),
                (
                    "after_message",
                    agir.lib.models.DescriptionField(
                        help_text="Note montrée à l'utilisateur une fois la question répondue.",
                        verbose_name="Note après avoir répondu",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date de début"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "answers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Chaque personne répondant sera associé au tag correspondant.",
                        related_name="answers",
                        to="activity.announcementanswer",
                        verbose_name="Réponses",
                    ),
                ),
                (
                    "associated_answers_tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tags associés",
                        related_name="banner_announcement_persontag",
                        to="activity.bannerannouncementanswertag",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Segment des personnes auquel ce message sera montré",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banner_announcement_notifications",
                        related_query_name="notification",
                        to=settings.NUNTIUS_SEGMENT_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bannière d'annonce",
                "verbose_name_plural": "Bannières d'annonce",
            },
        ),
        migrations.CreateModel(
            name="AnnouncementActivity",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="date de création",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="dernière modification"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID interne à l'API pour identifier la ressource",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("D", "Présentée au destinataire"),
                            ("C", "Le destinataire a fermé l'annonce"),
                        ],
                        default="D",
                        max_length=1,
                        verbose_name="Etat",
                    ),
                ),
                (
                    "banner_announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="activity.bannerannouncement",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="people.person"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["person", "banner_announcement"],
                        name="banner_announcement_person",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="announcementactivity",
            constraint=models.UniqueConstraint(
                fields=("person", "banner_announcement"),
                name="unique_person_banner_announcement",
            ),
        ),
    ]
