# Generated by Django 3.2.25 on 2024-12-10 10:13

import agir.lib.model_fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting_proxies", "0006_auto_20240611_1438"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votingproxy",
            name="voting_dates",
            field=agir.lib.model_fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("2022-04-10", "10 avril 2022 — 1er tour de la présidentielle"),
                        ("2022-04-24", "24 avril 2022 — 2nd tour de la présidentielle"),
                        ("2022-06-12", "12 juin 2022 — 1er tour des législatives"),
                        ("2022-06-19", "19 juin 2022 — 2nd tour des législatives"),
                        (
                            "2024-06-09",
                            "Dimanche 9 juin 2024 (samedi 8 juin pour la Guadeloupe, la Martinique, la Guyane, la Polynésie française et les Français·es de l'étranger résidant sur le continent américain) — Élections européennes 2024",
                        ),
                        (
                            "2024-06-30",
                            "Dimanche 30 juin 2024 (samedi 29 juin pour la Guadeloupe, la Martinique, la Guyane, la Polynésie française et les Français·es de l'étranger résidant sur le continent américain) — 1er tour des législatives",
                        ),
                        (
                            "2024-07-07",
                            "Dimanche 7 juillet 2024 (samedi 6 juillet pour la Guadeloupe, la Martinique, la Guyane, la Polynésie française et les Français·es de l'étranger résidant sur le continent américain) — 2nd tour des législatives",
                        ),
                        (
                            "2025-01-12",
                            "Dimanche 12 Janvier 2025 - 1er tour des législatives partielles",
                        ),
                        (
                            "2025-01-19",
                            "Dimanche 19 Janvier 2025 - 2nd tour des législatives partielles",
                        ),
                    ],
                    max_length=255,
                    verbose_name="date du scrutin",
                ),
                default=list,
                size=None,
                verbose_name="dates de disponibilité",
            ),
        ),
        migrations.AlterField(
            model_name="votingproxyrequest",
            name="voting_date",
            field=models.DateField(
                choices=[
                    (
                        datetime.date(2022, 4, 10),
                        "10 avril 2022 — 1er tour de la présidentielle",
                    ),
                    (
                        datetime.date(2022, 4, 24),
                        "24 avril 2022 — 2nd tour de la présidentielle",
                    ),
                    (
                        datetime.date(2022, 6, 12),
                        "12 juin 2022 — 1er tour des législatives",
                    ),
                    (
                        datetime.date(2022, 6, 19),
                        "19 juin 2022 — 2nd tour des législatives",
                    ),
                    (
                        datetime.date(2024, 6, 9),
                        "Dimanche 9 juin 2024 (samedi 8 juin pour la Guadeloupe, la Martinique, la Guyane, la Polynésie française et les Français·es de l'étranger résidant sur le continent américain) — Élections européennes 2024",
                    ),
                    (
                        datetime.date(2024, 6, 30),
                        "Dimanche 30 juin 2024 (samedi 29 juin pour la Guadeloupe, la Martinique, la Guyane, la Polynésie française et les Français·es de l'étranger résidant sur le continent américain) — 1er tour des législatives",
                    ),
                    (
                        datetime.date(2024, 7, 7),
                        "Dimanche 7 juillet 2024 (samedi 6 juillet pour la Guadeloupe, la Martinique, la Guyane, la Polynésie française et les Français·es de l'étranger résidant sur le continent américain) — 2nd tour des législatives",
                    ),
                    (
                        datetime.date(2025, 1, 12),
                        "Dimanche 12 Janvier 2025 - 1er tour des législatives partielles",
                    ),
                    (
                        datetime.date(2025, 1, 19),
                        "Dimanche 19 Janvier 2025 - 2nd tour des législatives partielles",
                    ),
                ],
                verbose_name="date du scrutin",
            ),
        ),
    ]
