# Generated by Django 4.2.18 on 2025-02-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0034_alter_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persontag",
            name="label",
            field=models.CharField(max_length=100, unique=True, verbose_name="nom"),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="label",
            field=models.CharField(max_length=100, unique=True, verbose_name="nom"),
        ),
    ]
