# Generated by Django 4.2.18 on 2025-02-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0037_eventsubtype_default_visibility_alter_event_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsubtype",
            name="send_email_to_group_members",
            field=models.BooleanField(
                default=True,
                verbose_name="Envoyer un mail aux membres du groupe organisateur lorsque l'événement sera crée sur AP",
            ),
        ),
    ]
