# Generated by Django 4.2.18 on 2025-02-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0038_eventsubtype_send_email_to_group_members_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsubtype",
            name="send_email_to_group_members",
            field=models.BooleanField(
                default=True,
                verbose_name="Envoyer mail et notifications aux membres du groupe organisateur lorsque l'événement sera crée sur AP",
            ),
        ),
    ]
