# Generated by Django 3.2.25 on 2024-11-13 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0034_alter_document_type'),
        ('groups', '0019_supportgroup_membership_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='has_finance_managing_privilege',
            field=models.BooleanField(default=True, editable=False, help_text='La valeur de ce champ indique si la personne aura le droit de gérer les finances du groupe et de créer/suivre/valider des demandes de dépense. N.B. Cette propriété est valable uniquement pour les gestionnaires dans les boucles départementales et seulement pour les animateur·ices de groupe local', verbose_name='Accès à la gestion des finances du groupe'),
        ),
        migrations.CreateModel(
            name='MembershipRemoveRequest',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date de création')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="UUID interne à l'API pour identifier la ressource", primary_key=True, serialize=False, verbose_name='UUID')),
                ('details', models.TextField(max_length=1000, verbose_name='Details')),
                ('reason_type', models.CharField(choices=[('milite_plus_lfi', 'Cette personne ne milite plus à la France Insoumise'), ('jamais_participee', "Cette personne n'a jamais participé au groupe d'action"), ('change_groupe', 'Cette personne a changé de groupe'), ('demande_suppression', 'Cette personne a demandé sa suppression du groupe')], default='demande_suppression', max_length=20, verbose_name='Raison de la suppression')),
                ('solved', models.BooleanField(default=False, verbose_name='Résolu')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='people.person')),
                ('person', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='membership_remove_requests', to='people.person')),
                ('supportgroup', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='membership_remove_requests', to='groups.supportgroup')),
            ],
            options={
                'verbose_name': 'Requête suppression de membre',
                'verbose_name_plural': 'Requêtes de suppression de membre',
            },
        ),
    ]
