# Generated by Django 3.2.25 on 2025-01-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0054_alter_segment_newsletters'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='born_isnull',
            field=models.BooleanField(blank=True, null=True, verbose_name='Personnes sans date de naissance'),
        ),
    ]
